# Assignment 4 - Numpy arrays Pt. 2 Basic File I/O


## Authors
V. Aquiviva and B.W. Holwerda

## Learning Goals
* Getting started on Python plot.
* Syntax of python 

## Keywords
python, syntax, jupyter notebook, numpy, file I/O

## Companion Content


## Summary
This is the first of two assignments to learn the first steps into python programming 

And now some credits. A lot of this material is gratefully adapted from

http://github.com/jrjohansson/scientific-python-lectures.

This work is licensed under a CC-BY license. and from

https://github.com/jakevdp/WhirlwindTourOfPython.git

The text is released under the CC-BY-NC-ND license, and code is released under the MIT license.

<hr>


## Student Name and ID:



## Date:

<hr>

# More on manipulating arrays; basic file I/O

As usual, we are very grateful to J.R. Johansson at [http://github.com/jrjohansson/scientific-python-lectures](http://github.com/jrjohansson/scientific-python-lectures).

And we also use material from

http://www.scipy-lectures.org/intro/numpy/operations.html

and

https://github.com/jakevdp/PythonDataScienceHandbook (02.08)


In [1]:
# what is this line all about?!? Answer in lecture 4
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

## Manipulating arrays

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [2]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [3]:
A[1:3]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [4]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`. Indexing works exactly as we saw for strings.

In [5]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [6]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [7]:
A[:3] # first three elements

array([ 1, -2, -3])

In [8]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [9]:
A = np.array([1,2,3,4,5])

In [10]:
A[-1] # the last element in the array

5

In [11]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [12]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [13]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [14]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [15]:
# strides
A[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [16]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [17]:
row_indices = [1, 2, 3]
A[row_indices,:] #can also not use the : and just write A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [18]:
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [19]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices] 

array([11, 22, 34])

### Masks ###
We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [20]:
B = np.array(range(5))
B

array([0, 1, 2, 3, 4])

In [21]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [22]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [23]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [24]:
mask = (5 < x) * (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [25]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [26]:
mask = np.logical_and((5 < x),(x < 7.5))

In [27]:
mask = (5 < x) * (x < 7.5) #equivalent to above

In [28]:
len(x[mask]) 

4

### where

The index mask can be converted to position index using the `where` function

In [29]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [30]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([5.5, 6. , 6.5, 7. ])

In [31]:
np.where(x > 5)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),)

### Reshaping arrays

In [32]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [33]:
n, m = A.shape

In [34]:
n,m

(5, 5)

In [35]:
B = A.reshape((1,n*m))
B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [36]:
C = np.arange(30)
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
C.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### hstack and vstack

In [38]:
a = np.array([[1,2],[3,4]])
b= np.array([[5,6]])

In [39]:
b

array([[5, 6]])

In [40]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 

In [42]:
A = np.array([[1, 2], [3, 4]])

A

array([[1, 2],
       [3, 4]])

In [43]:
# now B is referring to the same array data as A 
B = A 

In [44]:
# changing B affects A
B[0,0] = 10

B

array([[10,  2],
       [ 3,  4]])

In [45]:
A

array([[10,  2],
       [ 3,  4]])

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [46]:
B = np.copy(A)

In [47]:
# now, if we modify B, A is not affected
B[0,0] = -5

B

array([[-5,  2],
       [ 3,  4]])

In [48]:
A

array([[10,  2],
       [ 3,  4]])

## Vectorizing functions

A basic rule of programming get good performance we should try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [49]:
def Theta(x):
    """
    Scalar implementation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [50]:
Theta(-10)

0

In [51]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

OK, that didn't work because we didn't write the `Theta` function so that it can handle a vector input... 

To get a vectorized version of Theta we can use the Numpy function `vectorize`. In many cases it can automatically vectorize a function:

In [52]:
Theta_vec = np.vectorize(Theta)

In [53]:
Theta_vec(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

We can also implement the function to accept a vector input from the beginning (requires more effort but might give better performance):

In [54]:
def Theta(x):
    """
    Vector-aware implementation of the Heaviside step function.
    """ 
    return 1 * (x >= 0)

In [55]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

## Using arrays in conditions

When using arrays in conditions,for example `if` statements and other boolean expressions, one needs to use `any` or `all`, which requires that any or all elements in the array evalutes to `True`:

In [56]:
M = np.array([[1, 2], [3, 6]])

In [57]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

at least one element in M is larger than 5


In [58]:
M > 5

array([[False, False],
       [False,  True]])

In [59]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("not all elements in M are larger than 5")

not all elements in M are larger than 5


## Type casting

Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions (see also the similar `asarray` function). This always create a new array of new type:

In [60]:
M.dtype

dtype('int64')

In [61]:
M2 = M.astype(float)

M2

array([[1., 2.],
       [3., 6.]])

In [62]:
M2.dtype

dtype('float64')

In [63]:
M3 = M.astype(bool)

M3

array([[ True,  True],
       [ True,  True]])

### Fast Sorting in NumPy: np.sort and np.argsort

Although Python has built-in sort and sorted functions to work with lists, NumPy's np.sort function turns out to be much more efficient and useful. 

To return a sorted version of the array without modifying the input, you can use np.sort:

In [64]:
x = np.array([2, 1, 4, 3, 5])

print(np.sort(x)) # does not change x

[1 2 3 4 5]


If you prefer to sort the array in-place, you can instead use the sort method of arrays:

In [65]:
x.sort()

print(x)


[1 2 3 4 5]


A related function is argsort, which instead returns the indices of the sorted elements:

In [66]:
x = np.array([2, 1, 4, 3, 5])

i = np.argsort(x)

print(i)

[1 0 3 2 4]


The first element of this result gives the index of the smallest element, the second value gives the index of the second smallest, and so on. These indices can then be used (via fancy indexing) to construct the sorted array if desired:

In [67]:
x[i]

array([1, 2, 3, 4, 5])

## Quick I/O from files (will do more in Pandas) 

Built-in Python commands are open(), read(), write(), close()

They are best explained through examples, for example those found at

https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

and also this nice lecture that I found while looking for examples

http://www.grapenthin.org/teaching/geop501/lectures/lecture_07_fileinput_output.pdf

For brevity's sake, we look at the more flexible options in numpy:
    
np.loadtxt()

np.genfromtxt()

np.savetxt()

np.genfromtxt() is more powerful than np.loadtxt() because it can gracefully 
handle missing data, so we'll just use that. 

In [68]:
np.genfromtxt?

Some useful parameters are: 

skipheader = N (skips N rows)

usecols = ... to specifywhich columns to read

delimiter= ‘,’  to define the delimiter (white space is default)

In [69]:
randomdata = np.random.rand(10,5)

In [70]:
randomdata

array([[0.83048876, 0.41846197, 0.90544876, 0.2604442 , 0.85401868],
       [0.14697734, 0.77753047, 0.55616376, 0.07320014, 0.13805688],
       [0.04213194, 0.71642563, 0.45245452, 0.21927758, 0.00782003],
       [0.53924489, 0.71245862, 0.20776469, 0.09989176, 0.78865456],
       [0.8773033 , 0.07038703, 0.06521151, 0.88034353, 0.84569504],
       [0.35438348, 0.8194442 , 0.38777646, 0.42937187, 0.49176823],
       [0.522796  , 0.61577688, 0.13693291, 0.43105751, 0.35744479],
       [0.96182672, 0.88753062, 0.8186153 , 0.60721498, 0.84720011],
       [0.31491014, 0.9122746 , 0.95731889, 0.01543259, 0.62962208],
       [0.51062848, 0.42092811, 0.0374086 , 0.25877839, 0.00112693]])

In [ ]:
np.savetxt('randomdata1.txt',randomdata,delimiter=',')






In [ ]:
!head randomdata1.txt

In [ ]:
np.savetxt('randomdata1.txt',randomdata,delimiter=',',fmt="%.3f")

In [ ]:
!head randomdata1.txt #(for Windows use type)

In [ ]:
data = np.genfromtxt('randomdata1.txt')

data

#### Aaagh! What happened?

In [ ]:
data = np.genfromtxt('randomdata1.txt',delimiter=',')

data

In [ ]:
#I can also do

data = np.genfromtxt('randomdata1.txt',skip_header=5,usecols= (2,3),delimiter=',')

data

# Exercises 

1. Generate a size 20 array populated by random numbers between 0 and 5; 
2. Create a mask that filters out the numbers smaller than 1; 
3. Return the new array; 
4. Sort the new array; 
5. Reverse-sort the new array; 
6. Write the new array to file, using one number per line; 
7. Read the file into a third array, skipping the first row 
8. Print the final array to screen.


